apps/df_goods/urls.py
from django.conf.urls import url,re_path
from django.views.static import serve
from tiaozao_shop import settings
from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^index/$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^detail/(\d+)/$', views.detail, name="detail"),
    url('^content/(\d+)/(\d+)/$', views.content, name="content"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
    re_path('^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT}),
]

apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url,re_path
from django.views.static import serve
from tiaozao_shop import settings
from .views import *
from . import viewsUtil

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    url(r'^publishers/$',publishers,name="publishers"),
    url(r'^changeInformation/$',changeInformation,name="changeInformation"),
    url(r'^check_user/$',check_user,name="check_user"),
    url('^myself_information/$', myself_information, name="myself_information"),
    url('^shoper_information/(.+)/$', shoper_information, name="shoper_information"),
    url('^message/$', message, name="message"),
    url('^person_message/$', person_message, name="person_message"),
    #url(r'^kefu_message/$', kefu_message, name="kefu_message"),
    url(r'^logout/$', logout, name="logout"),
    #显示验证码
    url(r'^verify_show/$', verify_show,name="verify_show"),
    url(r'^verifycode/$', viewsUtil.verify_code,name="verifycode"),
    #修改密码
    url(r'^changeInPwd/$', changeInPwd,name="changeInPwd"),
    #重置密码
    url(r'^findpwdView/$', findpwdView,name="findpwdView"),
    #退货
    url(r'^tuihuo/$', tuihuo,name="tuihuo"),
    re_path('^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT}),
]

tiaozao_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve  # 上传文件处理函数

from .settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置confurl
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT})
]

apps/df_order/models.py
from django.db import models
from datetime import datetime

from df_goods.models import GoodsInfo
from df_user.models import UserInfo

class OrderInfo(models.Model):  # 大订单
    oid = models.CharField(max_length=20, primary_key=True, verbose_name="大订单号")
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name="订单用户")
    odate = models.DateTimeField(auto_now=True, verbose_name="时间")
    oIsPay = models.BooleanField(default=False, verbose_name="是否支付")
    ototal = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="总价")
    oaddress = models.CharField(max_length=150, verbose_name="订单地址")
    # 虽然订单总价可以由多个商品的单价以及数量求得，但是由于用户订单的总价的大量使用，忽略total的冗余度

    class Meta:
        verbose_name = "未付款订单"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.user.uname + "在" + str(self.odate) + "的订单"
        return "{0}在的订单{1}".format(self.user.uname, self.odate)


# 无法实现：真实支付，物流信息
class OrderDetailInfo(models.Model):  # 大订单中的具体某一商品订单

    goods = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="商品")
    username=models.CharField(max_length=20, verbose_name="买家昵称", default=None)
    shopername = models.CharField(max_length=20, verbose_name="卖家昵称", default="")
    datatime = models.DateTimeField(verbose_name="交易时间",default=datetime.now)
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name="订单")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="商品价格")
    count = models.IntegerField(verbose_name="商品数")

    class Meta:
        verbose_name = "付款订单"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.goods.gtitle + "(数量为" + str(self.count)  + ")"
        return "{0}(数量为{1})".format(self.goods.gtitle, self.count)

apps/df_user/views.py
import uuid
from random import Random

from django.shortcuts import render,render_to_response
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.core.paginator import Paginator
from django.http import JsonResponse,HttpResponse

from hashlib import sha1

from django.contrib import messages

import df_goods
from df_goods.models import TypeInfo,GoodsInfo,GoodsContent,ContentChart
from df_cart.models import CartInfo
from .models import GoodsBrowser,UserInfo,Information,tuihuoInfo
from . import user_decorator
from df_order.models import *

from django.core.mail import send_mail


def register(request):

    context = {
        'title': '用户注册',
    }
    return render(request, 'df_user/register.html', context)


def register_handle(request):

    username = request.POST.get('user_name')
    password = request.POST.get('pwd')
    confirm_pwd = request.POST.get('confirm_pwd')
    email = request.POST.get('email')

    # 判断两次密码一致性
    if password != confirm_pwd:
        return redirect('/user/register/')
    # 密码加密
    s1 = sha1()
    s1.update(password.encode('utf8'))
    encrypted_pwd = s1.hexdigest()

    # 创建对象
    UserInfo.objects.create(uname=username, upwd=encrypted_pwd, uemail=email)
    # 注册成功
    context = {
        'title': '用户登陆',
        'username': username,
    }
    return render(request, 'df_user/login.html', context)


def register_exist(request):
    username = request.GET.get('uname')
    uemail = request.GET.get('uemail')
    count = UserInfo.objects.filter(uname=username).count()
    email_count=UserInfo.objects.filter(uemail=uemail).count()
    print(email_count)
    return JsonResponse({'count': count,'email_count':email_count})


def login(request):
    uname = request.COOKIES.get('uname', '')
    context = {
        'title': '用户登陆',
        'error_name': 0,
        'error_pwd': 0,
        'error_vc': 0,
        'uname': uname,
    }
    return render(request, 'df_user/login.html', context)

#验证码显示
def verify_show(request):
    return render(request,'df_user/login.html')

def login_handle(request):  # 没有利用ajax提交表单
    # 接受请求信息
    uname = request.POST.get('username')
    upwd = request.POST.get('pwd')
    jizhu = request.POST.get('jizhu', 0)
    vc = request.POST.get('vc')
    verifycode = request.session['verifycode']
    user = UserInfo.objects.filter(uname=uname)
    print("user:%s" %(user))
    if len(user) == 1:  # 判断用户密码并跳转
        s1 = sha1()
        s1.update(upwd.encode('utf8'))
        if s1.hexdigest() == user[0].upwd and vc == verifycode and user[0].uname_passOrfail == True:
            url = request.COOKIES.get('url', '/')
            red = HttpResponseRedirect(url)  # 继承与HttpResponse 在跳转的同时 设置一个cookie值
            # 是否勾选记住用户名，设置cookie
            if jizhu != 0:
                red.set_cookie('uname', uname)
            else:
                red.set_cookie('uname', '', max_age=-1)  # 设置过期cookie时间，立刻过期
            request.session['user_id'] = user[0].id
            request.session['user_name'] = uname
            return red
        elif s1.hexdigest() == user[0].upwd and vc != verifycode:
            context = {
                'title': '用户名登陆',
                'error_name': 0,
                'error_pwd': 0,
                'error_vc':1,
                'uname': uname,
                'upwd': upwd,
                'user': user,
                'vc':vc,
            }
            return render(request, 'df_user/login.html', context)
        elif user[0].uname_passOrfail == False:
            messages.success(request, "你的账号存在违规行为，已被封禁。")
            context = {
                'title': '用户名登陆',
                'uname': uname,
                'upwd': upwd,
                'user': user,
                'vc': vc,
            }
            return render(request, 'df_user/login.html',context)
        else:
            context = {
                'title': '用户名登陆',
                'error_name': 0,
                'error_pwd': 1,
                'error_vc': 1,
                'uname': uname,
                'upwd': upwd,
                'user':user,
                'vc': vc,
            }
            return render(request, 'df_user/login.html', context)
    else:
        context = {
            'title': '用户名登陆',
            'error_name': 1,
            'error_pwd': 0,
            'error_vc': 0,
            'uname': uname,
            'upwd': upwd,
            'user': user,
            'vc': vc,
        }
        return render(request, 'df_user/login.html', context)


def logout(request):  # 用户登出
    request.session.flush()  # 清空当前用户所有session
    return redirect(reverse("df_goods:index"))

#修改密码
#随机生成验证码
def random_str(randomlength=8):
    str = ''
    chars = 'abcdefghijklmnopqrstuvwsyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    length = len(chars) - 1
    random = Random()
    for i in range(randomlength):
        str += chars[random.randint(0, length)]
    return str
#发送邮件重置密码
def findpwdView(request):
    context = {
        'title': '重置密码',
    }
    if request.method=="POST":
        username = request.POST.get("username")
        email = request.POST.get("email")
        print("username:%s" % (username))
        user = UserInfo.objects.get(uname=username)
        context = {
            'title': '重置密码',
            'user': user,
        }
        if user.uemail == email:
            email_title = "跳蚤市场-重置密码"
            code = random_str()  # 随机生成的验证码
            request.session["code"] = code  # 将验证码保存到session
            email_body = "您的密码已重置，为了您的账号安全，请勿将密码泄露。新的密码为：{0}".format(code)
            # send_mail的参数分别是 邮件标题，邮件内容，发件箱(settings.py中设置过的那个)，收件箱列表(可以发送给多个人),失败静默(若发送失败，报错提示我们)
            send_status = send_mail(email_title, email_body, 'woaisilaowu@163.com', [email],fail_silently=False)
            code=request.session["code"] #获取传递过来的验证码
            # 密码加密
            s1 = sha1()
            s1.update(code.encode('utf8'))
            encrypted_pwd = s1.hexdigest()
            user.upwd = encrypted_pwd
            user.save()
            del request.session["code"]  # 删除session
            messages.success(request, "密码已重置，请登录邮箱接受重置密码！")
        else:
            messages.success(request, "用户邮箱与输入邮件不匹配，重置失败！")

        return render(request,"df_user/change_password1.html",context)
    return render(request, "df_user/change_password1.html",context)

@user_decorator.login
def info(request):  # 用户中心
    uid=request.session['user_id']
    user = UserInfo.objects.get(id=uid)
    browser_goods = GoodsBrowser.objects.filter(user=user).order_by("-browser_time")
    cart_num = CartInfo.objects.filter(user_id=int(uid)).count()
    goods_list = []
    if browser_goods:
        goods_list = [browser_good.good for browser_good in browser_goods]  # 从浏览商品记录中取出浏览商品
        explain = '最近浏览'
    else:
        explain = '无最近浏览'

    context = {
        'title': '用户中心',
        'page_name': 1,
        'guest_cart': 1,
        'cart_num':cart_num,
        'user_phone': user.uphone,
        'user_address': user.uaddress,
        'user_name': user.uname,
        'user':user,
        'ucheck_passOrfail':user.ucheck_passOrfail,
        'goods_list': goods_list,
        'explain': explain,
    }
    return render(request, 'df_user/user_center_info.html', context)


@user_decorator.login
def order(request, index):
    user_id = request.session['user_id']
    orders_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()
    tuohuo_infos = tuihuoInfo.objects.filter()
    paginator = Paginator(orders_list, 2)
    page = paginator.page(int(index))
    user = UserInfo.objects.get(id=request.session['user_id'])
    context = {
        'paginator': paginator,
        'page': page,
        # 'orders_list':orders_list,
        'title': "用户中心",
        'user':user,
        'page_name': 1,
        'guest_cart': 1,
        'cart_num':cart_num,
        'tuohuo_infos':tuohuo_infos,
    }
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def site(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    cart_num = CartInfo.objects.filter(user_id=user.id).count()
    if request.method == "POST":
        user.ushou = request.POST.get('ushou')
        user.uaddress = request.POST.get('uaddress')
        user.uyoubian = request.POST.get('uyoubian')
        user.uphone = request.POST.get('uphone')
        user.save()
    context = {
        'page_name': 1,
        'title': '用户中心',
        'user': user,
        'guest_cart': 1,
        'cart_num':cart_num,
    }
    return render(request, 'df_user/user_center_site.html', context)
#发布商品
@user_decorator.login
def publishers(request):
    user = UserInfo.objects.get(id=request.session['user_id'])
    cart_num = CartInfo.objects.filter(user_id=user.id).count()
    typeinfos = TypeInfo.objects.all()
    if request.method == "POST":
        gtitle = request.POST.get('title')
        gpic = request.FILES.get('pic')
        gunit = user.uname
        gprice = request.POST.get('price')
        gjianjie = request.POST.get('jianjie')
        gkucun = request.POST.get('kucun')
        gcontent = request.POST.get('content')
        gtype_id = request.POST.get('type_id')
        if gtitle=="" or gpic=="" or gprice=="" or gjianjie=="" or gkucun=="" or gcontent=="":
            messages.success(request, "请完整填充信息！")
        elif int(gprice) >=100000:
            messages.success(request, "价格不能大于100000！")
        else:
            GoodsInfo.objects.create(gtitle=gtitle, gpic=gpic, gunit=gunit, gprice=gprice,gjianjie=gjianjie, gkucun=gkucun, gcontent=gcontent, gtype_id=gtype_id)
            messages.success(request, "发布商品成功")



    context = {
        'page_name': 1,
        'title': '用户中心',
        'user': user,
        'typeinfos':typeinfos,
        'guest_cart': 1,
        'cart_num': cart_num,
    }
    return render(request, 'df_user/user_publishers.html', context)
#修改资料、头像
@user_decorator.login

templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
            <div class="information clearfix">
                <a href="/user/myself_information/"><img src="{{ MEDIA_URL }}{{ user.ulogo }}" alt="头像"></a>
                <div class="information1 clearfix">
                    {% if user.ucheck_passOrfail == False %}
                        <a>未实名认证</a>
                    {% else %}
                        <a style="color: cyan">已实名认证</a>
                    {% endif %}
                </div>
            </div>
			<ul>
				<li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
                <li><a href="{% url "df_user:check_user" %}">· 实名认证</a></li>
                <li><a href="{% url "df_user:publishers" %}">· 发布商品</a></li>
                <li><a href="{% url "df_user:changeInformation" %}">· 修改资料</a></li>
                <li><a href="{% url "df_user:changeInPwd" %}">· 修改密码</a></li>
				<li><a href="{% url "df_user:order" 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
                {% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">订单号：{{ orderinfo.oid }}</li>
					<li class="col02 stress">已支付</li>
                    <li class="col02 stress">
                        {% for tuohuo_info in tuohuo_infos %}
                            {% if tuohuo_info.order_number == orderinfo.oid and tuohuo_info.passOrdefault == False %}
                                正在申请退款
                            {% elif tuohuo_info.order_number == orderinfo.oid and tuohuo_info.passOrdefault %}
                                退款通过
                            {% endif %}
                        {% endfor %}
                    </li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="50%">
                                {% for order_detail in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ MEDIA_URL }}{{ order_detail.goods.gpic }}"></li>
                                    <li class="col02">{{ order_detail.goods.gtitle }}<em class="good_price">{{ order_detail.goods.gprice }}</em>元&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;卖家:<em>{{ order_detail.goods.gunit }}</em></li>
									<li class="col03">{{ order_detail.count }}件</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="10%">{{ orderinfo.ototal }}元</td>
							<td width="10%">已付款</td>
							<td width="10%"><a href="#" class="oper_btn">查看物流</a></td>
                            <td width="10%"><a href="#" class="oper_btn">评论</a></td>
                            <td width="10%"><a href="{% url "df_user:tuihuo" %}" class="oper_btn">退货</a></td>
						</tr>
					</tbody>
				</table>
			    {% endfor %}


				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="{% url "df_user:order" page.previous_page_number %}">上一页</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        {% if index == page.number %}
                            <a href="{% url "df_user:order" index %}" class="active">{{ index }}</a>
                        {% else %}
                            <a href="{% url "df_user:order" index %}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page.has_next %}
					    <a href="{% url "df_user:order" page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
	</div>

    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元');
            }

        )
        }
    )

    </script>

{% endblock center_body %}

templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
            <div class="information clearfix">
                <a href="/user/myself_information/"><img src="{{ MEDIA_URL }}{{ user.ulogo }}" alt="头像"></a>
                <div class="information1 clearfix">
                    {% if user.ucheck_passOrfail == False %}
                        <a>未实名认证</a>
                    {% else %}
                        <a style="color: cyan">已实名认证</a>
                    {% endif %}
                </div>
            </div>
			<ul>
                <li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
                <li><a href="{% url "df_user:check_user" %}">· 实名认证</a></li>
                <li><a href="{% url "df_user:publishers" %}">· 发布商品</a></li>
                <li><a href="{% url "df_user:changeInformation" %}">· 修改资料</a></li>
                <li><a href="{% url "df_user:changeInPwd" %}">· 修改密码</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con1">
					<dl>
                        <dt>收件人：{{ user.ushou }}</dt>
                        <dt>电话：{{ user.uphone }}</dt>
                        <dt>当前地址：{{ user.uaddress }}</dt>
{#                        <a href="/user/place_order" style="display: block; width: 80px; height:30px; line-height: 30px; text-align: center;font-size: 13px; " class="info_submit">提交订单</a>#}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="{% url "df_user:site" %}" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
                        <div class="form_group">
                            <label>手机：</label>
                            <input type="text" name="uphone" value="{{ user.uphone }}">
                        </div>
                        <div class="form_group">
                            <label>邮编：</label>
                            <input type="text" name="uyoubian" value="{{ user.uyoubian }}">
                        </div>
                        <div class="form_group form_group2">
                            <label>详细地址：</label>
                            <textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
                        </div>
						<input type="submit" name="" value="修改地址" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{% endblock center_body %}

templates/df_user/user_changePwd.html
{% extends 'base.html' %}
{% block script %}
        <script type="text/javascript">
            {% if error_info %}
                xtalert.alertError('{{ error_info }}')
            {% endif %}
            {% if info %}
                 xtalert.alertInfo('{{ info }}')
            {% endif %}
            {% if success_info %}
                 xtalert.alertSuccessToast('{{ success_info }}！');
            {% endif %}
        </script>
 {% endblock %}
{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <div class="information clearfix">
                <a href="/user/myself_information/"><img src="{{ MEDIA_URL }}{{ user.ulogo }}" alt="头像"></a>
                <div class="information1 clearfix">
                    {% if user.ucheck_passOrfail == False %}
                        <a>未实名认证</a>
                    {% else %}
                        <a style="color: cyan">已实名认证</a>
                    {% endif %}
                </div>
            </div>
			<ul>
                <li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
                <li><a href="{% url "df_user:check_user" %}">· 实名认证</a></li>
                <li><a href="{% url "df_user:publishers" %}">· 发布商品</a></li>
                <li><a href="{% url "df_user:changeInformation" %}">· 修改资料</a></li>
                <li><a href="{% url "df_user:changeInPwd" %}" class="active">· 修改密码</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">

				<h3 class="common_title2">修改密码</h3>
				<div class="site_con">
					<form action="{% url "df_user:changeInPwd" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<div class="form_group_logo">
							<img src="{{ MEDIA_URL }}{{ user.ulogo }}"  alt="头像">
						</div>
                        <div class="form_group">
                            <label>新密码：</label>
                            <input type="text" name="password">
                        </div>
                        <div class="form_group">
                            <label>确认密码：</label>
                            <input type="text" name="password2">
                        </div>
						<input type="submit" name="" value="修改" class="info_submit">
					</form>
				</div>
		</div>
	</div>

{#  弹窗提示  #}
    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}
{% endblock center_body %}

templates/df_user/user_check_username.html
{% extends 'base.html' %}
{% block center_body %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <div class="information clearfix">
                <a href="/user/myself_information/"><img src="{{ MEDIA_URL }}{{ user.ulogo }}" alt="头像"></a>
                <div class="information1 clearfix">
                    {% if user.ucheck_passOrfail == False %}
                        <a>未实名认证</a>
                    {% else %}
                        <a style="color: cyan">已实名认证</a>
                    {% endif %}
                </div>
            </div>
			<ul>
                <li><a href="{% url "df_user:info" %}">· 个人信息</a></li>
                <li><a href="{% url "df_user:check_user" %}" class="active">· 实名认证</a></li>
                <li><a href="{% url "df_user:publishers" %}">· 发布商品</a></li>
                <li><a href="{% url "df_user:changeInformation" %}">· 修改资料</a></li>
                <li><a href="{% url "df_user:changeInPwd" %}">· 修改密码</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· 全部订单</a></li>
				<li><a href="{% url "df_user:site" %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">

				<h3 class="common_title2">用户实名认证</h3>
				<div class="site_con">
					<form action="{% url "df_user:check_user" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
						<div class="form_group">
							<label>真实姓名：</label>
							<input type="text" name="name" class="user_info_check">
						</div>
                        <div class="form_group">
                            <label>证件类型：</label>
                            <select name="type_id" class="user_info_check">
                              <option value="大陆身份证">大陆身份证</option>
                              <option value="港澳台身份证">港澳台身份证</option>
                              <option value="护照">护照</option>
                            </select>
                        </div>
                        <div class="form_group">
							<label>证件号码：</label>
							<input type="text" name="tel" class="user_info_check">
						</div>
                        <div class="form_group">
                            <label>上传证件图片：</label>
                            <input type="file" name="pic" class="user_info_check">
                        </div>
						<input type="submit" name="" value="发布" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{#  弹窗提示  #}
    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}
{% endblock center_body %}