apps/df_cart/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'df_cart'

urlpatterns = [
    url(r'^$', views.user_cart, name="cart"),
    url(r'^add(\d+)_(\d+)/$', views.add, name="add"),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name="edit"),
    url(r'^delete(\d+)/$', views.delete, name="delete"),
]

apps/df_goods/urls.py
from django.conf.urls import url,re_path
from django.views.static import serve
from tiaozao_shop import settings
from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^index/$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^detail/(\d+)/$', views.detail, name="detail"),
    url('^content/(\d+)/(\d+)/$', views.content, name="content"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),  # 全文检索
    re_path('^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT}),
]

apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url,re_path
from django.views.static import serve
from tiaozao_shop import settings
from .views import *
from . import viewsUtil

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    url(r'^publishers/$',publishers,name="publishers"),
    url(r'^changeInformation/$',changeInformation,name="changeInformation"),
    url(r'^check_user/$',check_user,name="check_user"),
    url('^myself_information/$', myself_information, name="myself_information"),
    url('^shoper_information/(.+)/$', shoper_information, name="shoper_information"),
    url('^message/$', message, name="message"),
    url('^person_message/$', person_message, name="person_message"),
    #url(r'^kefu_message/$', kefu_message, name="kefu_message"),
    url(r'^logout/$', logout, name="logout"),
    #显示验证码
    url(r'^verify_show/$', verify_show,name="verify_show"),
    url(r'^verifycode/$', viewsUtil.verify_code,name="verifycode"),
    #修改密码
    url(r'^changeInPwd/$', changeInPwd,name="changeInPwd"),
    #重置密码
    url(r'^findpwdView/$', findpwdView,name="findpwdView"),
    #退货
    url(r'^tuihuo/$', tuihuo,name="tuihuo"),
    re_path('^media/(?P<path>.*)/$',serve,{'document_root':settings.MEDIA_ROOT}),
]

tiaozao_shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve  # 上传文件处理函数

from .settings import MEDIA_ROOT


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),  # 使用富文本编辑框配置confurl
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT})
]

templates/base.html
{% extends 'base_foot.html' %}

{% block body %}
    <div class="header_con" id="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到跳蚤市场!</div>
			<div class="fr">
{#                判断是否已经登录#}
                {% if request.session.user_name|default:'' != '' %}
{#                    default过滤器进行判断如果request.session.user_name不等于空字符串则用户登陆状态为true#}
{#                    也就是说当用户为已登陆状态时则显示用户名#}

{#                    class="login_info fl"#}
				<div class="login_btn fl">
                    <img class="img-circle" align="center" src="{{ MEDIA_URL }}{{ user.ulogo }}" alt="头像"/>
                    <font color="#ff4500">{{ request.session.user_name }}</font>
				</div>
                <div class="login_btn fl">
                    <span>|</span>
                    <em><a href="{% url "df_user:logout" %}">退出</a></em>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url "df_user:login" %}">登录</a>
					<span>|</span>
					<a href="{% url "df_user:register" %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url "df_user:info" %}">用户中心</a>
                    <span>|</span>
					<a href="{% url "df_user:message" %}">消息中心</a>
					<span>|</span>
					<a href="{% url "df_cart:cart" %}">我的购物车</a>
					<span>|</span>
					<a href="{% url "df_user:order" 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>


    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo1.png"></a>
{#        {% if page_name == 1 %}#}
{#            <div class="sub_page_name fl">{{ title }}</div>#}
{#        {% endif %}#}
		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("请输入搜索内容");
                        }
                        else{
                            location.href = '{% url "df_goods:ordinary_search" %}?q='+q+'&page=1'
                        }
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>

        {% if guest_cart == 1 %}
            <div class="guest_cart fr">
                <a href="{% url "df_cart:cart" %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">{{ cart_num }}</div>
            </div>
        {% else %}
            <div class="guest_cart fr">
                <a href="{% url "df_cart:cart" %}" class="cart_name fl">我的购物车</a>
                <div class="goods_count fl" id="show_count">0</div>
            </div>
        {% endif %}
	</div>
{% block content %}
{% endblock content %}
{% block center_body %}
{% endblock center_body %}


{% endblock body %}

templates/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>跳蚤市场 | {{ title }}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{#    <link href="/static/css/style1.css" rel="stylesheet" type="text/css">#}
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{#	<script type="text/javascript" src="/static/js/register.js"></script>#}
    {% block head %}{% endblock head %}
    {% block script %}{% endblock script %}
</head>
<body>

{% block body %}{% endblock body %}

    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2020 大佬说的都对 All Rights Reserved</p>
		<p>电话：***-*******    京ICP备********号</p>
	</div>

</body>
</html>